### ISSUE TITLE
[Feature] Add  a Better scaling algorithm

### ISSUE THREAD

**Issue by eromoe** [dtgDTGdtg/SRWE#10]
Hi, 

This program is the only one works for rpgmaker games, amazing !

Now It seems just enlarge the window to certain size, I think it would be much more better to use a good scaling algorithm to render the window . Is this possible?

**Comment by FransBouma** [comment]
That's what SRWE does: it enlarges the window (by sending the window specific windows messages, the same way as when you'd resize it manually). The application then has to anticipate on that: resize its viewport or do nothing and let DXGI resize the image (which is what you're seeing). See the readme text on the SRWE page: https://github.com/dtgDTGdtg/SRWE#hotsampling-games-for-screenshots
