### ISSUE TITLE
See flashing wave on some game

### ISSUE THREAD

**Issue by eromoe** [dtgDTGdtg/SRWE#11]
Hi,

I meet this problem on a RPG maker game(not all, only one now).
I can see all texture show flashing wave  while character moving. Texture is refered to floor, walls, trees or something else. I tried to capture game window by a gif recorder, but the captured gif didn't show this problem as playing. This hurt my eyes,  do you have any idea ?

**Comment by FransBouma** [comment]
Nope, not a thing caused by SRWE, as it simply resizes the window frame which triggers the app (if it supports it, a lot of games don't) to resize its viewport. Apparently the game you're using it with doesn't do this.
