### ISSUE TITLE
problem with Anthem

### ISSUE THREAD

**Issue by dul3l3s** [dtgDTGdtg/SRWE#14]
Hello, I used the program during the intro of Anthem and it worked great! However, after the game fully installed the display won't scale up to 5760x1080. The resolution reverts back to 2445. Any ideas on how to fix? Using Windows 10 on an Asus RTX2060 with updated Nvidia drivers

**Comment by FransBouma** [comment]
run game in windowed mode, not borderless window or fullscreen. However sometimes a game resizes the viewport limited to the desktop size, and it then requires adjustments inside the game engine, which is outside the scope of srwe.
