### ISSUE TITLE
Not working with latest Windows 10 Updates 

### ISSUE THREAD

**Issue by SALFATOR** [dtgDTGdtg/SRWE#15]
As the title says SRWE not changing Width and heights accordingly after Latest Updates by Microsoft .. !

**Comment by FransBouma** [comment]
in what game? Latest windows 10 updates mean: 1903? You can manually resize the window with the mouse? You run both game and srwe as admin?

**Comment by SALFATOR** [comment]
Hello sir didn't expect someone would reply to me .. sorry for not providing extra info .. 
it was working just Fine as always until updating my windows to the latest Patch which i regret it as always . 
anyways the game is Skyrim SE and running as ADMIN along with SRWE as well . 
Windows 10 Home 1903 . 
after selecting the game and putting my desire W , H my screen freezes and nothing shows at all . 
upon selecting  Fake full screen it comes back and the game working just fine as it should be..! 
any numbers i choose the same outcome appears to me which is nothing at all ..

**Comment by FransBouma** [comment]
Hmm. And if you resize the window manually? (so the game runs windowed (not borderless!)), can you resize it with the mouse?
Also, in windows settings, could you disable the windows game bar? (I think it's under gaming). Not sure if it's disableable, I have windows 10 1809 so can't test locally)

**Comment by SALFATOR** [comment]
Yes it's re-sizable with the mouse normally as it should be .. 
and yes the game bar could be disabled normally ..

**Comment by FransBouma** [comment]
If you disable the gamebar, does it work then? If it doesn't make a difference, I don't know what's wrong, it should work fine. I don't have windows 10 1903 so I can't test here...

**Comment by SALFATOR** [comment]
Yes since you've mentioned it already i tried it and makes no difference at all !! 
I don't know what's the issue here really strange. all was good before the patch i'm really confused .!

**Comment by FransBouma** [comment]
I don't know either, sorry. If you open notepad, and attach srwe to notepad, and then specify a different size, does notepad resize? If so, windows at least isn't the problem, but what it is, I have no idea, sorry...

**Comment by Jendowoz** [comment]
So am I SAFFATOR I'm having the same issue, Frans, except I'm playing in Sims 4 and when I try to use SRWE in the game to take good quality shots, the screen goes white and nothing happens. It was fine before the latest windows update.

**Comment by FransBouma** [comment]
If you check 'Force EXITSIZEMOVE' it should work, it works with other games on 1903. If not, then I don't know, sorry

**Comment by Jendowoz** [comment]
Thank you! thank you! That was all I needed to do, it’s a fantastic program and you should be really proud of it. 

Sent from Mail for Windows 10

**Comment by SALFATOR** [comment]
Hello FransBouma , 
Could you Please Check this shared [Video ](https://www.youtube.com/watch?v=Iefj12gbFHY&feature=youtu.be).. Which indicate my issue we talk before about

**Comment by FransBouma** [comment]
yeah but you picked an application which isn't resizable by hand either. What srwe does is simply what you also do with the mouse: if you can't resize it with the mouse, you can't resize it with srwe.

Try notepad. It will work properly (I'm on 1903, works fine)

**Comment by SALFATOR** [comment]
Okay you're right i tried it with Note bad and works perfectly  ! 
But for games won't work at all .. made me confused really ! 
the display window splitting each time i resize, also reverting back to W :1536 and H : 864 after i alt+tab to my game screen .

**_As below before and after_** 
![ScreenShot2298](https://user-images.githubusercontent.com/30498481/66530714-39e43180-eb09-11e9-8b87-3f5933910d1f.png)
![ScreenShot2299](https://user-images.githubusercontent.com/30498481/66530715-3a7cc800-eb09-11e9-8322-fec5bfa646d0.png)

**Comment by FransBouma** [comment]
If you did everything as above, and you tested whether running the game/srwe as admin or not as admin, force exitsizemove on or off all don't make a difference, then I don't know what's causing it...
