### ISSUE TITLE
SRWE settings is kinda funky, 

### ISSUE THREAD

**Issue by judyz04** [dtgDTGdtg/SRWE#16]
I used to use this program and i wanted to try it out again today. and it was in windowed mode and everything. but when i tried to change the proportions of the screen, it like automatically changed for me. leaving me with [this](https://viragosims.tumblr.com/post/611144189309255680/hey-guys-i-was-wondering-if-anyone-knows-how-to). was wondering if it is fixable.

**Comment by FransBouma** [comment]
the game autocorrects it, most likely. SRWE just resizes the window as if you did that manually with the mouse, nothing else. So if the game corrects that again, it can't do much about that
