### ISSUE TITLE
'unhandled exception'

### ISSUE THREAD

**Issue by xtxbae1** [dtgDTGdtg/SRWE#17]
Hi hope ya'll are well. 
When I try to select running applications, I get a notification saying 'unhandled exception has occured in your application' . When I click continue, my application  doesn't turn up. When I click quit, and re-try the process the result is the same. Any help would be much appreciated!
![Annotation 2020-05-02 230657](https://user-images.githubusercontent.com/64711151/80893392-cc2c6c80-8cc9-11ea-88f5-2db4a2a1773e.png)

**Comment by SALFATOR** [comment]
Run it as Administrator .

**Comment by FransBouma** [comment]
Running as admin makes it go away indeed. It's however a small bug in SRWE. When I ported the code over to a camera client for games I ran into this and found out it's mainly to do with that srwe doesn't have the rights to get info regarding a process that windows reports is running. If you run srwe as admin this doesn't occur.

**Comment by FransBouma** [comment]
Working on fix with a guard clause

**Comment by FransBouma** [comment]
Fixed
