### ISSUE TITLE
Adding integer scaling ability

### ISSUE THREAD

**Issue by donizettilorenzo** [dtgDTGdtg/SRWE#18]
Do you consider to continue the development of this application maybe adding the integer scaling possibility?

https://github.com/Marat-Tanalin/integer-scaling

**Comment by FransBouma** [comment]
It's mainly in maintenance mode. I've added similar functionality (with aspect ratio correction like the tool you refer to) to my IGCS camera system some time ago so people don't need a separate tool anymore.
