### ISSUE TITLE
Always Auto Attach & Apply desired Profile | Toggle Borders

### ISSUE THREAD

**Issue by r3sus** [dtgDTGdtg/SRWE#26]
Hello and thanks a lot for your tool.

There are some suggestions:

Always Auto Attach, not only on startup, and Apply desired Profile.
I think, something similar is presented in Borderless software.
But the more familiar example to me is Cheat Engine that has setting to hook processes by name from list. Thus application can be restarted and tool will attach it automatically.
There might be a list of Process - Profile for auto-apply. 

Toggle Borders, not only remove. 
Sometimes it useful to return back minimize and close buttons.

Restore all changes made to window.
For now I go to game settings and change something. 

Maintain initial window size in settings for easier re-scale. 
In case I want to vary scale for initial window size, to find more suitable value.
For now tool multiplies dimensions, and sets scale to 1. Changing scale since then is applied to modified dimensions, not initial, making it scale different.

Thanks.

**Comment by FransBouma** [comment]
Thanks for the suggestions. I don't see a lot of new features being added to this tool tho, so to be honest don't get your hopes up that these are included soon. But you'll never know :)

**Comment by andkirby** [comment]
Auto Attach is most desirable.
All what I need to set a profile for list of processes automatically.
It would be really appreciated.

**Comment by andkirby** [comment]
![image](https://user-images.githubusercontent.com/1828532/146421921-f488dfcd-8985-4fa9-b51c-bb0d8345a782.png)
Possibly this configuration is invented to make it, but it does not work.

**Comment by mistenkt** [comment]
@andkirby @r3sus 

Hope i dont step on any feets here @FransBouma, but having used this app for so long and also really missed some of those features i took the liberty to create my own app that makes applying exisitng profiles a little easier. Heavily inspired by SRWE, with a lot less advanced features when it comes to the actual window management part, but i focused mostly on making applying existing profiles easier. I have also implemented a beta auto apply feature there, but even without it not having to manually select processes and presets every time is probably a welcomed feature for some. 

I'll gladly remove this comment if you dont like me mentioning it here, but seeing as this project hasnt received updates for 3 years i hopefully dont step on any feet.

https://github.com/mistenkt/resize-raccoon

**Comment by FransBouma** [comment]
@mistenkt this project is basically archived, as the hotsampling feature we screenshotters use it for the most is nowadays built-in into my camera tools anyway so this tool is rarely used. So if you built another app that might help people out with the same needs, sure why not :)
