### ISSUE TITLE
(Question, probably wrong tag)

### ISSUE THREAD

**Issue by OneSlize** [dtgDTGdtg/SRWE#27]
How does SRWE interacting with anti cheat. Does it hook onto the window is it safe to use for multiplayer games? Thanks in advance and neat program guys.

**Comment by FransBouma** [comment]
It's safe to use for anti-cheat as all it does is sending window messages to the window, which is exactly the same as if you had resized the window with the mouse, manually. So it doesn't hook anything. It does attach to teh process tho. 

But as most anti-cheat software hides the window/process for other processes, srwe can't attach to the process, so I doubt any game with anti-cheat is available to srwe. If it is, you can safely use it.

**Comment by OneSlize** [comment]
Gotcha thanks
