### ISSUE TITLE
Is there an option to hide the taskbar?

### ISSUE THREAD

**Issue by karpiyon** [dtgDTGdtg/SRWE#30]
Great Job, Thanks you for this.
Is there an option to hide the taskbar?

If not I can implement it in the code.
The thing is that the following only get a handle to the main desktop and i need to show/hide it for all desktops.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;

namespace SRWE
{
    public class Taskbar
    {
        [DllImport("user32.dll")]
        private static extern int FindWindow(string className, string windowText);

        [DllImport("user32.dll")]
        private static extern int ShowWindow(int hwnd, int command);

        [DllImport("user32.dll")]
        public static extern int FindWindowEx(int parentHandle, int childAfter, string className, int windowTitle);

        [DllImport("user32.dll")]
        private static extern int GetDesktopWindow();

        private const int SW_HIDE = 0;
        private const int SW_SHOW = 1;

        protected static int Handle
        {
            get
            {
                return FindWindow("Shell_TrayWnd", "");
            }
        }

        protected static int HandleOfStartButton
        {
            get
            {
                var handleOfDesktop = GetDesktopWindow();
                var handleOfStartButton = FindWindowEx(handleOfDesktop, 0, "button", 0);
                return handleOfStartButton;
            }
        }

        private Taskbar()
        {
            // hide ctor
        }

        public static void Show()
        {
            ShowWindow(Handle, SW_SHOW);
            ShowWindow(HandleOfStartButton, SW_SHOW);
        }

        public static void Hide()
        {
            ShowWindow(Handle, SW_HIDE);
            ShowWindow(HandleOfStartButton, SW_HIDE);
        }
    }
}
```

**Comment by FransBouma** [comment]
Hiding taskbars is not what the tool will do, as it's core focus is manipulating the window selected. Hiding taskbars means it will change things outside the attached process and that's not what the tool should do, as it will then be unclear to the user what else it will do and people might not use it because of that. 

If you use it for changing game window windows, you can use the fake fullscreen button which will make the window go over the taskbar.

**Comment by MagnusMagnuson** [comment]
> If you use it for changing game window windows, you can use the fake fullscreen button which will make the window go over the taskbar.

This does not seem to work. Fake fullscreen will fill out the whole screen, but the taskbar is still on top and blocking the bottom.
