### ISSUE TITLE
after recent cod warzone update no longer detecting the cod exe

### ISSUE THREAD

**Issue by blitznats** [dtgDTGdtg/SRWE#31]
1st thanks a lot its the only program that fake that fullscreen in a windowed mode the game forces my monitor to HDR mode unless in windowed mode)
recently after the 20 gb update on pc with the launch of recochet anticheat the SRWE program doenst detect Cod exe (the other programs detect cod)
i would really appreciate it if you can take a look
thanks again

**Comment by FransBouma** [comment]
what other programs detect cod if srwe can't? It checks with windows which processes are available. If there's anti-cheat in the game it likely hides the exe from windows so srwe can't see it (and that's not fixable). perhaps the game runs as admin tho, so running srwe as admin might fix it, other than that, it's something that's not fixable from my side, sorry

**Comment by blitznats** [comment]
i found others they show the name of the exe with symbols they do the work but am not sur about the same performance anyway thank you for your time i appreciate it, hope it changes in the future
thanks again
