### ISSUE TITLE
I can’t save a profile in SRWE

### ISSUE THREAD

**Issue by pilootfreddy** [dtgDTGdtg/SRWE#33]
I am trying with the Microsoft Flight Simulator 2020 to fly on 3 monitors (1440 x 900 each).
When I have adjusted the screens on a resolution (4320 x 900), how should I save this profile; the “Save” key does not work in SRWE.

**Comment by FransBouma** [comment]
what does 'doesn't work' mean, it gave an error, it didn't save anything, etc... 
In any case, the button is greyed out if you haven't loaded a profile, so first load a profile, then alter it, then you can save it. It's cumbersome, I know, it's how the original author wrote it and it wasn't really changed after that. You can also copy/paste the xml files on disk btw and edit those, this is usually faster.

**Comment by pilootfreddy** [comment]
Thanks Frans
