### ISSUE TITLE
It doesn't seem to detect games

### ISSUE THREAD

**Issue by lyndonguitar** [dtgDTGdtg/SRWE#37]
It seems to detect every single process/window except for the game I am running. am I missing anything? some option to set perhaps?

**Comment by FransBouma** [comment]
if you run the game as administrator, you have to run srwe also as administrator. Tho in general you don't need to run a game as administrator. (legitimate copies, that is).

Another issue might be that the game uses anticheat software. This usually hides the process from other processes so srwe won't see it. There's little you can do about that.
