### ISSUE TITLE
1x 34" and 2x 27"

### ISSUE THREAD

**Issue by Jeppemaskin** [dtgDTGdtg/SRWE#40]
Hello..
I have 1x 3440x1440 21:9 (34" 21:9)  and 2x 2560x1440 (27" 16:9) on the sides.

I get this problem, where the bezels "should" be is like 5 inches in on my centre screen, not where my screens seperate.

(ignore the "minus bezel setting"), it's just to show what my problem is. The screenshot is the exact size as my main monitor.
So when i change size screen angel it's getting wierd. etc.

Is it possible to change that offset to be 3440x1440, instead of, im guessing, 2560x1440?

King regards
![2e4c373c9a9ef6ec64cc244a3fb2558c](https://user-images.githubusercontent.com/121693320/210109740-ccd7e1a0-d052-40c3-9e4a-abb0974d40a2.jpg)

**Comment by FransBouma** [comment]
srwe only resizes the window, it doesn't do anything else. You can specify how large the window should be in the srwe dialog. If the game then decides to do something else after that (clamp it to the desktop or whatever) then that's up to the game. You can specify whatever you want, so e.g. if you want 3440x1440, type that in and click Set. Teh window is then resized to that size
