### ISSUE TITLE
Windows 11 Scaling

### ISSUE THREAD

**Issue by sirhideo** [dtgDTGdtg/SRWE#41]
Does windows scaling affect SRWE resizing?  I have triple monitors setup as below.

Middle : 32" 3840 x 2160p (scale to 175%)
Left and Right: 15" Portait 1200 x 2160 (scale to 175%)

So the entire resolution should be 6240 x 2160.  However if I set this resolution on SRWE it would be way bigger.  How can I get the correct pixel? Thanks!

**Comment by FransBouma** [comment]
SRWE sends a WM_SIZE message to the application with the new size you specified (in pixels). It's up to the application how to deal with that; Some resize the window and then the viewport, others resize the viewport and with that the window, and others do nothing. So it depends on your application what the end result will be.
