### ISSUE TITLE
Srwe window is skewed

### ISSUE THREAD

**Issue by cory1970** [dtgDTGdtg/SRWE#45]
When I download the file. Unzip it, the window that pops up has everything jumbled together in a smaller window. HELP 🙏

**Comment by FransBouma** [comment]
SRWE is a windows forms app and sadly isn't really compatible with HiDPI windows settings. This is an unfixable limitation

**Comment by cory1970** [comment]
Thanks for the reply. I did figure out that if I lowered my dpi it would work But adds a few steps. Running triple 43 inch 4k TVs. Now I can’t get the task bar to go away in game. Any suggestions sir?

**Comment by FransBouma** [comment]
No sorry... :(
