### ISSUE TITLE
SRWE doesn’t work on new laptop 

### ISSUE THREAD

**Issue by eriiicaaa** [dtgDTGdtg/SRWE#46]
I use SRWE to take high quality pictures for sims 4 and everything works fine on my old laptop. But I recently bought a new laptop with the newest 40 series NVIDIA GPUS and 4K UHD. I don’t know what made SRWE not working but the program turned out all pressed together like I couldn’t see the numbers. Tried the older versions too and everything looked like it should except it was blurry and I couldn’t change the resolutions. The game itself had issues with the resolutions so I decided to send the laptop back. Now I’m looking for a new one but I still don’t know if it was the 4k UHD who caused the issue or something else? Should it work with 2560x1600 resolutions and the 40 series GPU?

**Comment by FransBouma** [comment]
Please see: https://github.com/dtgDTGdtg/SRWE/issues/45

So it's not your laptop's 4K display, windows uses a HiDPI setting (and scaling of windows, buttons etc. as well) and the way SRWE is built doesn't support that. There are ways to 'fix it' a bit, but they always break one way or the other (like the tree on the left won't look ok, no matter what) so this is sadly not fixable.
