### ISSUE TITLE
Details in comment

### ISSUE THREAD

**Issue by davidozz0** [dtgDTGdtg/SRWE#48]
Hello,

if it's possible, I would like 2 features:

1. when I open the software, I need to start the application and only after opened it, I can select the profile. Is there any solution to this?
2. auto-detect the application and set the proper profile, without having to select the profile

Thanks, I would appreciate even just a reply to this thread.

Davide

**Comment by FransBouma** [comment]
This app won't get any new features unless someone develops them. Sorry.

**Comment by davidozz0** [comment]
Ok, thanks for reply.
