### ISSUE TITLE
Programme not using the set higher resolution?

### ISSUE THREAD

**Issue by MrRetr0** [dtgDTGdtg/SRWE#50]
I'm quite new to this program, and haven't been able to find any information anywhere else. I'm trying to resize Cyberpunk 2077 from my monitors native resolution of 1440p up to 4K for extra fidelity in screenshots. However, even after running the game as admin, setting it to windowed mode, running SRWE as admin and selecting the game, I can't get it to go any higher than my native 1440p resolution. Every time I try setting it to 4K, it blows up the image so my screen is zoomed into the top left corner of the game - without actually changing the resolution. I've tried using the "Fake Fullscreen" option, but that just resets the image to 1440p. How do I set it to 4K?

**Comment by FransBouma** [comment]
cp doesn't support hotsampling so srwe doesn't work. my camera tools use special code to implement hotsampling on cp 2077
