### ISSUE TITLE
Virus Total

### ISSUE THREAD

**Issue by JSebastianRod** [dtgDTGdtg/SRWE#51]
That means any issue?

https://www.virustotal.com/gui/file/c919f2885b6c4d7a0821a00e1152a41401a3279dfa531e4ecf3da4f881fb5294

**Comment by FransBouma** [comment]
No, this is what is called a 'false positive'. The "ML" in the virusscanner stands for 'machine learning' and they use AI to find patterns that *might* be harmful. SRWE attaches to a process and therefore has code to do that. Some virusscanners think if an app attaches to another process it is thus vulnerable. It's not in this case :) You can safely ignore it
