### ISSUE TITLE
SRWE 236 not recognize another disk

### ISSUE THREAD

**Issue by ddsracingfl** [dtgDTGdtg/SRWE#52]
Hello, download SRWE on disk C: (this disk is main disk for Win 11 system etc), all my games from steam installed on disk D:, such as ACC, I copied to D: open SRWE, click on Select Running Application and I could not find disk D:, show me disk C: only, how switch to another disk?

Thank you,

**Comment by ricardomreis** [comment]
before you select running application you need first to start the game
