### ISSUE TITLE
Post SRWE Screenshots

### ISSUE THREAD

**Issue by elasticheartt** [dtgDTGdtg/SRWE#53]
Hello, I'm fairly new to hotsampling. I've been trying to hotsample Payday 2. SRWE does change the game's resolution since it gets bigger and it doesn't fit my monitor. But when I take a screenshot resolution still shows up as my native resolution instead of the resolution I had changed it to be. I've tried Afterburner, Reshade, Shadowplay and Steam so far to capture a screenshot. Am I doing something wrong? I'm not sure if the updates broke something with the game.

**Comment by FransBouma** [comment]
I don't know if the game supports hotsampling. At least run the game in windowed mode (so with a window, not a full screen window) and then try to set it to a higher resolution. If you use borderless fullscreen or fullscreen the window might resize but the contents is just stretched.
