### ISSUE TITLE
Window settings revert on focus shift for certain games.

### ISSUE THREAD

**Issue by RobertWarton** [dtgDTGdtg/SRWE#9]
Hey. Love the program, but I am running into an issue on certain types of games (specifically Earth Defense Force). The settings work when selected in SRWE, however when the focus shifts to the game window, the settings are reverted. I think it happens in games that lock the cursor to the screen, but I'm not entirely sure.

Any help would be appreciated.

Thanks.

**Comment by FransBouma** [comment]
What exactly do you mean with 'the settings work when selected in SRWE. What exactly do you set and what effect do these settings have? E.g. do you change the resolution and is the game window then indeed resized and when you go back to the game window it is again resized to what it was?

**Comment by FransBouma** [comment]
No reply since... 3 years? :)
